### ISSUE TITLE
Custom actions buttons are inactive

### ISSUE THREAD

**Issue by a-l-h** [ChrisYounger/config_explorer#21]
Hello Chris,

Huge thanks for your App, I use it every day, it makes everything easier! 🙏🏻🙏🏻🙏🏻

I have just discovered custom actions so I am trying to set one from the provided examples first.

My local/config_explorer.conf:

```
[global]
write_access = true
run_commands = true

[action:restart_splunk]
label = restart splunk
action = run-safe:echo restart splunk triggered; nohup sh -c "sleep 2; ./bin/splunk restart" >/dev/null 2>1 &
order = 90
```

The 'restart splunk' button appears but remains inactive: it is not clickable, the cursor does not switch to a hand when mousing over.

Not sure if I missed something of if it is an issue.

Thanks again,

Alexis

**Comment by ChrisYounger** [comment]
Hi Alexis, glad the app is helpful to you.  Interesting problem, I am not sure why it is happening as it seems like you have done the correct steps. Can you please give me some more information so I can try find out the root cause?  What browser are you using?  Do the default buttons (such as btool check) work correctly?  Can you provide a screenshot?

Thanks for reporting this issue and your assistance

* edit maybe also try using your browser  in incognito mode (because this usually disables browser extensions) and also try a different browser.

**Comment by a-l-h** [comment]
Hello Chris,

Sorry for the very late answer.

It turns out that it must be a company Chrome browser related issue because:
- OK on company Edge browser
- OK on company Chrome browser in private window
- KO on company Chrome
- OK on personal Chrome

Thanks anyhow for the feedback and thanks a lot again for the App!

**Comment by ChrisYounger** [comment]
Thanks for the update
